name: Check Version
on:
  schedule:
    # 03:32 every day
    - cron:  '32 03 * * *'
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check for version
      run: |
        set -e
        eval "$(grep '^ARG ' Dockerfile | sed 's/^ARG /export /')"
        UPSTREAM_VERSION="$(curl https://api.github.com/repos/$REPOSITORY/releases/latest | jq -r '.name')"
        [ "$VERSION" = "$UPSTREAM_VERSION" ]
    - name: IRC Message Action
      uses: Gottox/irc-message-action@master
      if: failure()
      with:
        channel: "Gottox"
        nickname: gh-gottox
        message: "Gottox: https://github.com/${{ github.repository }} New version"
