name: Docker Push

on: 
- push
- create

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Docker Build
      run: |
        repo=$(echo "${{ github.repository }}" | tr 'A-Z' 'a-z')
        ref=$(echo "${{ github.ref }}" | tr 'A-Z' 'a-z')
        docker build -t docker.pkg.github.com/$repo:$ref .
    - name: Docker Login
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Docker Push
      run: |
        repo=$(echo "${{ github.repository }}" | tr 'A-Z' 'a-z')
        ref=$(echo "${{ github.ref }}" | tr 'A-Z' 'a-z')
        docker push docker.pkg.github.com/${{ github.repository }}:${{ github.ref }}
    - name: IRC Message Action
      uses: Gottox/irc-message-action@master
      if: failure()
      with:
        channel: "##gottox"
        nickname: gh-gottox
        message: "Gottox: https://github.com/${{ github.repository }} failed on ${{ github.event.action }} ${{ github.event.compare }}"
